(in-package #:coding-math)

(defsketch postcards3d((width 800)
                       (height 800)
                       (focal-length 1)
                       (max-depth 500)
                       (shapes (loop for x from 1 to 100
                                     collect (list (rand-int -1000 1000)
                                                   (rand-int -1000 1000)
                                                   (rand-int 1 max-depth)))))
  (text (format nil "focal length: ~f" focal-length) 20 20)
  (translate (/ width 2) (/ height 2))
  (dolist (shape shapes)
    (destructuring-bind (x y z) shape
      (let ((persp (/ focal-length (+ z focal-length))))
        ;; (text (format nil "x: ~,2$ ~% y: ~,2$ ~% persp: ~,2$" x y persp) 20 20)
        (push-matrix)
        (scale persp)
        (translate x y)
        (circle 0 0 50)
        (if (<= z 1)
            (setf (third shape) max-depth)
          (decf (third shape) 0.2))
        (pop-matrix))))
  )

(defmethod kit.sdl2:mousewheel-event ((window postcards3d) ts x y)
  (with-slots (focal-length) window
    (incf focal-length (* 1 y))))
;; (make-instance 'postcards3d)
