(in-package #:coding-math)

(defsketch mini-lerp ((width 800)
                      (height 800)
                      (minx 50)
                      (maxx (- width 50))
                      (miny 100)
                      (maxy (- height 100))
                      (min-alpha 0)
                      (max-alpha 1)
                      (min-radius 10)
                      (max-radius 400)
                      (ts 0))
  (incf ts 0.005)
  (setf ts (wrap ts 0 1))
  (with-pen (make-pen :fill (rgb 0 0 0 (lerp ts max-alpha min-alpha)))
            (circle (lerp ts minx maxx) (lerp ts miny maxy) (lerp ts min-radius max-radius))))

; (make-instance 'mini-lerp)
